# Generated by Django 4.2.4 on 2023-09-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('owner_contact', models.BigIntegerField()),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default='', max_length=10)),
                ('store_name', models.CharField(max_length=200)),
                ('Nomor_Induk_Berusaha', models.BigIntegerField()),
                ('Kode_BLI', models.BigIntegerField()),
                ('store_contact', models.BigIntegerField()),
                ('beginning_capital', models.BigIntegerField()),
                ('store_channel', models.CharField(max_length=100)),
                ('store_channel_photo', models.ImageField(default=False, upload_to='product_photos/')),
                ('owner_resume', models.FileField(default='', upload_to='')),
                ('owner_country', models.CharField(max_length=100)),
                ('owner_city', models.CharField(max_length=100)),
                ('store_milestone', models.TextField()),
                ('business_type', models.CharField(max_length=100)),
                ('Challenges', models.TextField()),
                ('store_handphone_number', models.BigIntegerField()),
                ('products', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendors', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
