# Generated by Django 4.2.4 on 2023-09-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umkm',
            old_name='Challenges',
            new_name='challenges',
        ),
        migrations.RenameField(
            model_name='umkm',
            old_name='Kode_BLI',
            new_name='kode_BLI',
        ),
        migrations.RenameField(
            model_name='umkm',
            old_name='Nomor_Induk_Berusaha',
            new_name='nomor_induk_berusaha',
        ),
    ]
