# Generated by Django 4.2.4 on 2023-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0002_rename_challenges_umkm_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='store_channel_photo',
            field=models.ImageField(default=False, upload_to='GrowBiz/UMKM/'),
        ),
    ]
