# Generated by Django 4.2.4 on 2023-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0003_alter_umkm_store_channel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='owner_resume',
            field=models.FileField(max_length=254, upload_to='GrowBiz/UMKM/'),
        ),
    ]
