# Generated by Django 4.2.4 on 2023-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0006_remove_umkm_owner_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='owner_resume',
            field=models.FileField(blank=True, max_length=254, upload_to='GrowBiz/UMKM/'),
        ),
        migrations.AddField(
            model_name='umkm',
            name='store_channel_photo',
            field=models.ImageField(blank=True, default=False, upload_to='GrowBiz/UMKM/'),
        ),
    ]
