# Generated by Django 4.2.4 on 2023-09-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0007_umkm_owner_resume_umkm_store_channel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='email',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='owner_city',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='owner_contact',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='owner_country',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='products',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='store_handphone_number',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='vendors',
        ),
    ]
