# Generated by Django 4.2.4 on 2023-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0008_remove_umkm_birth_date_remove_umkm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='beginning_capital',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='kode_BLI',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='nomor_induk_berusaha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='store_contact',
            field=models.CharField(max_length=200),
        ),
    ]
