# Generated by Django 4.2.4 on 2023-09-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0009_alter_umkm_beginning_capital_alter_umkm_kode_bli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='owner_resume',
        ),
    ]
