# Generated by Django 4.2.4 on 2023-09-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0010_remove_umkm_owner_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='store_channel_photo',
        ),
    ]
