# Generated by Django 4.2.4 on 2023-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0011_remove_umkm_store_channel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='store_channel_photo',
            field=models.ImageField(blank=True, upload_to='GrowBiz/UMKM/'),
        ),
    ]
