# Generated by Django 4.2.4 on 2023-09-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0012_umkm_store_channel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='store_channel_photo',
        ),
    ]
