# Generated by Django 4.2.4 on 2023-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default=True, upload_to='GrowBiz/courses/')),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_start', models.DateField()),
                ('class_end', models.DateField()),
                ('total_mentee', models.IntegerField(default=0)),
                ('link_meeting', models.URLField()),
                ('pdf_book', models.URLField()),
                ('join_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default=False, upload_to='GrowBiz/courses/')),
                ('lesson', models.ManyToManyField(to='courses.lesson')),
            ],
        ),
    ]
