# Generated by Django 4.2.4 on 2023-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.BigIntegerField()),
                ('outcome', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Pemasukan', 'Pemasukan'), ('Pengeluaran', 'Pengeluaran')], default='', max_length=15)),
                ('description', models.TextField()),
                ('amount_of_money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
