# Generated by Django 4.2.4 on 2023-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='income',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
