# Generated by Django 4.2.4 on 2023-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='GrowBiz/Investor/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='GrowBiz/Portfolio/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='GrowBiz/incubation/')),
                ('business_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('criteria', models.TextField()),
                ('investor', models.ManyToManyField(blank=True, to='incubation.investor')),
                ('portfolio', models.ManyToManyField(blank=True, to='incubation.portfolio')),
            ],
        ),
    ]
