# Generated by Django 4.1.1 on 2023-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='medical_description',
        ),
    ]
